version: '3'
services: 
  mysql-db:
    image: 'mysql:8.4'
    ports: 
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: root321
      MYSQL_DATABASE: db_test
      MYSQL_USER: user_test
      MYSQL_PASSWORD: test123
    networks: 
      - 'db-network'
    volumes: 
      - mysql-data:/var/lib/mysql
      - ./mysql-conf:/etc/mysql/mysql.conf.d
  
  adminer:
    image: 'adminer:5.0.6'
    ports: 
      - '8081:8080'
    networks: 
      - 'db-network'
networks:
  db-network:
volumes:
  mysql-data: