version: '3'
services: 
  mysql-db:
    image: 'mysql:5.7'
    ports: 
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: root321
      MYSQL_DATABASE: db_test
      MYSQL_USER: user_test
      MYSQL_PASSWORD: test123
    networks: 
      - 'db-network'
    volumes: 
      - ./database-data:/var/lib/mysql
  
  adminer:
    image: 'adminer'
    ports: 
      - '8081:8080'
    networks: 
      - 'db-network'
networks:
  db-network:
